import "@fontsource/geist-mono"
import "@fontsource-variable/m-plus-1"
import "./abstract/fonts.css"
import "./abstract/theme.css"
import "./abstract/default.css"
import "./abstract/typography.css"
import "./abstract/slidev.css"
import "./abstract/shiki.css"
